# Generated by Django 5.1.2 on 2024-11-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
    ]
